query gamePlayers(
  $sid: Int! # 服id
  $id_type: String! # pid: 角色ID, xdid: 心动Id
  $ids: [String]! # id 数组
) {
  gamePlayers(sid: $sid, id_type: $id_type, ids: $ids) {
    account # 账号
    pid # 角色id
    name # 角色昵称
    sid # 服id
    time # 创角时间
  }
}
