query servers(
  $first: Int!
  $page: Int!
  $ids: [Int]
  $name: String
  $created_at_from: DateTime
  $created_at_to: DateTime
) {
  servers(
    first: $first
    page: $page
    ids: $ids
    name: $name
    order_by: $order_by
    created_at: { from: $created_at_from, to: $created_at_to }
  ) {
    data {
      id
      name # 名称
      code # 编码
      sid # 日志ID
      url # 请求地址
      is_disable # 是否禁用
      created_at # 创建时间
      updated_at # 更新时间
    }
    paginatorInfo {
      count
      currentPage
      lastPage
      total
    }
  }
}